name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: deps
      run: sudo apt-get -y golang-go

    - name: Test
      run: make test
