name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0

    - name: deps
      run: sudo apt-get -y golang-go

    - name: Test
      run: make test
