name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: deps
      run: apt-get install golangci-lint golang-go

    - name: Build
      run: make
    
